### ISSUE TITLE
Google account support?

### ISSUE THREAD

**Issue by ferazambuja** [jwtlake/pokemon-go-helper#2]
Is it implemented? I get "ERROR: 401 Unauthorized".
[Error: Received code 403 from Google login. This could be because your account has 2-Step-Verification enabled. If that is the case, you need to generate an App Password and use that instead of your regular password: https://security.google.com/settings/security/apppasswords]

My account doesn't support that :(

Thanks

**Comment by jwtlake** [comment]
Ahh thanks. I'll have to look into it. I kinda think this is a feature pogobuf will need to add. I'm using his library to do the login actions. But before that I really need to improve the error handling so we can get a better idea what is going wrong in these cases.

**Comment by jwtlake** [comment]
I think we might have a fix for this in the latest version. Special thanks to nandiheath!

**Comment by ferazambuja** [comment]
It works 👍
