### ISSUE TITLE
2 step verification

### ISSUE THREAD

**Issue by darioLanderos** [jwtlake/pokemon-go-helper#3]
I believe this app is not working with a 2 step verification with a Google account, am I wrong?

**Comment by jwtlake** [comment]
Ahh wait no you are correct. 2 step verification is not supported. That functionality would actually be part of pogobuf. I'm not exactly sure how 2 step verification works. Is it tied to IP address or each application somehow? Could you just log into gmail or some other google service on the server to validate and then use the application after 2 step verification was completed for that device?

**Comment by ferazambuja** [comment]
https://pokeadvisor.com and some other apps get an authorization key to work.

Might be [this.](https://developers.google.com/identity/protocols/OAuth2)

**Comment by jwtlake** [comment]
I believe we have a fix for this in the latest version. Special thanks to nandiheath!

**Comment by jwtlake** [comment]
I believe we have this fixed so I'm going to close this for now. Let me know if anyone is still having issues.
